spring:
  datasource:
    url: jdbc:h2:mem:clinic_test;DB_CLOSE_DELAY=-1;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.redisson.spring.starter.RedissonAutoConfigurationV2

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-test.sql

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.clinic.appointment: debug
